sudo: required
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
before_install:
  - gem install bundler -v 1.16.2
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
